version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 15
- package-ecosystem: composer
  version: v2
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 15

  
