name: Node.JS Checks
on: [push, pull_request]

jobs:
  format: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.JS
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies
        run:  npm ci
      - name: Run tests
        run:  npm run test
      - name: Fix issues automatically
        if: failure()
        run: npm run fix && git add .
      - name: Commit changed files
        if: failure()
        uses: stefanzweifel/git-auto-commit-action@v4
        with: 
          commit_message: "Automatically fixing lint errors"
          
