name: PHP Checks

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: MilesChou/composer-action@master
      with:
           args: install
    - uses: MilesChou/composer-action@master
      with:
           args: test
    - uses: MilesChou/composer-action@master
      with:
           args: fix
      env:
        CI: true
