name: Format code using Prettier
on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install Dependencies
        run: npm ci
      - name: Lint CSS
        run: npm run lint --fix
      - name: Check format
        if: failure() || !failure()
        run: npx prettier --check .
      - name: Format code
        if: failure()
        run: npx prettier --write .
      - name: Commit changed files
        if: failure()
        uses: stefanzweifel/git-auto-commit-action@v3
        with:
          commit_message: "style: format code"
